Repository WITHUS-K/WITHUS-FE, pull requests merged in 2025-05, with the labels that each got.

#23 [feat] 2차 공통 컴포넌트 UI
  packages/ui/package.json
  packages/ui/src/components/DatePicker/DatePicker.css.ts
  packages/ui/src/components/DatePicker/DatePicker.stories.tsx
  packages/ui/src/components/DatePicker/DatePicker.tsx
  packages/ui/src/components/DatePicker/MonthSelect.tsx
  packages/ui/src/components/DatePicker/index.ts
  packages/ui/src/components/ToggleSwitch/SimpleToggleSwitch/SimpleToggleSwitch.css.ts
  packages/ui/src/components/ToggleSwitch/SimpleToggleSwitch/SimpleToggleSwitch.stories.tsx
  packages/ui/src/components/ToggleSwitch/SimpleToggleSwitch/SimpleToggleSwitch.tsx
  packages/ui/src/components/ToggleSwitch/TextToggleSwitch/TextToggleSwitch.css.ts
  packages/ui/src/components/ToggleSwitch/TextToggleSwitch/TextToggleSwitch.stories.tsx
  packages/ui/src/components/ToggleSwitch/TextToggleSwitch/TextToggleSwitch.tsx
  packages/ui/src/components/ToggleSwitch/index.ts
  packages/ui/src/icons/assets/colored/ic_touch_down.svg
  packages/ui/src/icons/src/colored/IcTouchDown.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/util/datePicker.ts
  pnpm-lock.yaml
Labels: ✨Feature, 🎨Design, 🌻유빈

#25 [feat] 회원가입, 로그인, 비밀번호 관련 api 연동 및 api 세팅
  apps/web/package.json
  apps/web/src/api/.gitkeep
  apps/web/src/api/api.ts
  apps/web/src/api/auth.ts
  apps/web/src/api/fetch.ts
  apps/web/src/api/fetchPublic.ts
  apps/web/src/api/index.ts
  apps/web/src/api/login.ts
  apps/web/src/api/serverSideTokens.ts
  apps/web/src/api/types.ts
  apps/web/src/app/(auth)/join/[step]/@modal/(.)club-search/page.tsx
  apps/web/src/app/(auth)/join/[step]/[[...modal]]/page.tsx
  apps/web/src/app/(auth)/join/[step]/layout.tsx
  apps/web/src/app/(auth)/join/_components/ClubItem/ClubItem.css.ts
  apps/web/src/app/(auth)/join/_components/ClubItem/ClubItem.tsx
  apps/web/src/app/(auth)/join/_components/ClubSearchContent/ClubSearchContent.tsx
  apps/web/src/app/(auth)/join/_components/Step2/Step2.tsx
  apps/web/src/app/(auth)/join/_components/Step3/Step3Admin.tsx
  apps/web/src/app/(auth)/join/_components/Step3/Step3User.tsx
  apps/web/src/app/(auth)/join/_context/ClubContext.tsx
  apps/web/src/app/(auth)/password/[step]/StepPageClient.tsx
  apps/web/src/app/(auth)/password/_components/Form/FindForm.tsx
  apps/web/src/app/(auth)/password/_components/Form/ResetForm.tsx
  apps/web/src/app/(auth)/password/_components/Form/VerifyForm.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/page.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/[time]/page.tsx
  apps/web/src/app/(main)/page.tsx
  apps/web/src/app/login/_components/LoginForm/LoginForm.tsx
  apps/web/src/app/page.tsx
  apps/web/src/components/providers/Providers.tsx
  apps/web/src/middleware.ts
  apps/web/src/routes.ts
  apps/web/src/store/constants/queryKeys.ts
  apps/web/src/store/mutation/index.ts
  apps/web/src/store/mutation/useAdminJoinMutation.ts
  apps/web/src/store/mutation/useEmailCheckMutation.ts
  apps/web/src/store/mutation/useEmailConfirmMutation.ts
  apps/web/src/store/mutation/useEmailVerifyMutation.ts
  apps/web/src/store/mutation/useLoginMutation.ts
  apps/web/src/store/mutation/useOrgSearchMutation.ts
  apps/web/src/store/mutation/usePhoneConfirmMutation.ts
  apps/web/src/store/mutation/usePhoneVerifyMutation.ts
  apps/web/src/store/mutation/useResetPasswordMutation.ts
  apps/web/src/store/mutation/useUserJoinMutation.ts
  apps/web/src/store/query/QueryClientProvider.tsx
  apps/web/src/store/query/ServerFetchBoundary.tsx
  apps/web/src/store/query/getQueryClient.ts
  apps/web/src/store/query/index.ts
  apps/web/src/types/auth.ts
  apps/web/src/utils/clearTokens.ts
  apps/web/src/utils/getClientSideTokens.ts
  packages/ui/src/components/List/Accordion/AccordionContext.ts
  packages/ui/src/icons/assets/colored/error.svg
  packages/ui/src/icons/src/colored/IcClubModalError.tsx
  packages/ui/src/icons/src/colored/index.ts
  pnpm-lock.yaml
Labels: ✨Feature, 🍀채원

#30 [feat] option 컴포넌트 및 타임테이블, Toast 컴포넌트 수정
  apps/web/src/app/(main)/interview-evaluation/_components/CellRender/CellRenderer.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/page.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/CellRenderer.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/page.tsx
  apps/web/src/app/(main)/organization/@modal/(.)invite/page.tsx
  apps/web/src/components/TimeTable/SelectableTimeTable.tsx
  apps/web/src/components/TimeTable/TimeTable.css.ts
  apps/web/src/components/TimeTable/TimeTable.tsx
  apps/web/src/constants/.gitkeep
  apps/web/src/constants/timetable.ts
  apps/web/src/hooks/.gitkeep
  apps/web/src/hooks/useTimeTableData.ts
  apps/web/src/middleware.ts
  apps/web/src/routes.ts
  apps/web/src/utils/.gitkeep
  packages/ui/package.json
  packages/ui/src/components/Option/Option.stories.tsx
  packages/ui/src/components/Option/Option.tsx
  packages/ui/src/components/Option/Selectable/Selectable.css.ts
  packages/ui/src/components/Option/Selectable/Selectable.tsx
  packages/ui/src/components/Option/index.ts
  packages/ui/src/components/Radio/Radio.css.ts
  packages/ui/src/components/Radio/Radio.stories.tsx
  packages/ui/src/components/Radio/Radio.tsx
  packages/ui/src/components/Radio/index.ts
  packages/ui/src/components/Toast/Toast.css.ts
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useToast.tsx
Labels: ✨Feature, ♻️Refactor, 🍀채원

#34 [feat] 공고 리스트 및 지원서 미리보기 페이지 UI
  apps/web/src/app/(main)/application-list/_components/RecruitmentCard/RecruitmentCard.css.ts
  apps/web/src/app/(main)/application-list/_components/RecruitmentCard/RecruitmentCard.tsx
  apps/web/src/app/(main)/application-list/page.tsx
  apps/web/src/app/(main)/application-list/setting/_context/SettingContext.ts
  apps/web/src/app/(main)/application-list/setting/layout.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/AdditionalInfoPreview/AdditionalInfoPreview.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/_components/AdditionalInfoPreview/AdditionalInfoPreview.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/ApplicationPartPreview/ApplicationPartsPreview.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/BasicInfoPreview/BasicInfoPreview.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/_components/BasicInfoPreview/BasicInfoPreview.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/DateChip/DateChip.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/_components/DateChip/DateChip.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/FileUpload/FileUpload.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/_components/FileUpload/FileUpload.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/InfoField/InfoField.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/PreivewHeader/PreivewHeader.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/QuestionFileList/QuestionFileList.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/_components/QuestionFileList/QuestionFileList.tsx
  apps/web/src/app/(main)/application-list/setting/preview/page.css.ts
  apps/web/src/app/(main)/application-list/setting/preview/page.tsx
  apps/web/src/constants/application.ts
  apps/web/src/constants/recuritmentList.ts
  apps/web/src/types/application.ts
  packages/ui/src/components/DropDown/Dropdown.css.ts
  packages/ui/src/components/DropDown/SelectDropdown/SelectAcademicStatusDropdown.tsx
  packages/ui/src/components/DropDown/SelectDropdown/SelectAcademicStatusDropdownTriggerContent.tsx
  packages/ui/src/components/DropDown/index.ts
  packages/ui/src/components/Flex/Flex.tsx
  packages/ui/src/components/Input/Input.css.ts
  packages/ui/src/components/Input/QuestionInput.tsx
  packages/ui/src/components/Input/index.ts
  packages/ui/src/components/Text/Text.tsx
  packages/ui/src/icons/assets/colored/ic_application_file_upload.svg
  packages/ui/src/icons/assets/colored/ic_image.svg
  packages/ui/src/icons/assets/mono/ic_arrow_down.svg
  packages/ui/src/icons/assets/mono/ic_calender.svg
  packages/ui/src/icons/assets/mono/ic_copy.svg
  packages/ui/src/icons/assets/mono/ic_file_upload.svg
  packages/ui/src/icons/assets/mono/ic_modify.svg
  packages/ui/src/icons/assets/mono/ic_refresh.svg
  packages/ui/src/icons/assets/mono/ic_trash.svg
  packages/ui/src/icons/src/colored/Error.tsx
  packages/ui/src/icons/src/colored/IcApplicationFileUpload.tsx
  packages/ui/src/icons/src/colored/IcImage.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/ui/src/icons/src/mono/IcArrowDown.tsx
  packages/ui/src/icons/src/mono/IcCalender.tsx
  packages/ui/src/icons/src/mono/IcCopy.tsx
  packages/ui/src/icons/src/mono/IcFileUpload.tsx
  packages/ui/src/icons/src/mono/IcModify.tsx
  packages/ui/src/icons/src/mono/IcRefresh.tsx
  packages/ui/src/icons/src/mono/IcTrash.tsx
  packages/ui/src/icons/src/mono/index.ts
Labels: ✨Feature, 🎨Design, 🌻유빈

#35 [feat] 1.5차 스프린트 api 연동
  apps/web/src/api/auth.ts
  apps/web/src/api/fetch.ts
  apps/web/src/app/(main)/organization/@modal/(.)invite/page.tsx
  apps/web/src/app/(main)/organization/OrganizationPageClient.tsx
  apps/web/src/app/(main)/organization/[[...modal]]/page.tsx
  apps/web/src/app/(main)/organization/_components/InviteModal/InviteContent.tsx
  apps/web/src/app/(main)/organization/_components/InviteModal/InviteModal.css.ts
  apps/web/src/app/(main)/organization/_components/MemberAssignmentPanel/MemberAssignmentPanel.tsx
  apps/web/src/app/(main)/organization/_components/MemberAssignmentPanel/MemberListItem.tsx
  apps/web/src/app/(main)/organization/_components/MemberAssignmentPanel/MemberPanel.tsx
  apps/web/src/app/(main)/organization/_components/OrgList/OrgList.tsx
  apps/web/src/app/(main)/organization/_components/OrgListItem/OrgListItem.tsx
  apps/web/src/app/(main)/organization/_components/RolePalettePanel/RoleItem.tsx
  apps/web/src/app/(main)/organization/_components/RolePalettePanel/RolePalettePanel.tsx
  apps/web/src/app/(main)/organization/settings/Settings.tsx
  apps/web/src/app/(main)/organization/settings/page.tsx
  apps/web/src/store/constants/index.ts
  apps/web/src/store/constants/queryKeys.ts
  apps/web/src/store/mutation/useAddOrganizationRoleMutation.ts
  apps/web/src/store/mutation/useAssignOrganizationUsersMutation.ts
  apps/web/src/store/mutation/useAssignRoleToUserMutation.ts
  apps/web/src/store/mutation/useDeleteOrganizationUsersMutation.ts
  apps/web/src/store/mutation/useUpdateOrganizationRoleMutation.ts
  apps/web/src/store/query/useOrganizationMembersQuery.ts
  apps/web/src/store/query/useOrganizationRolesQuery.ts
  apps/web/src/store/query/useOrganizationUsersQuery.ts
  apps/web/src/store/query/useUserByEmailQuery.ts
  apps/web/src/types/organization.ts
  apps/web/src/utils/color.ts
  packages/ui/src/components/DropDown/SelectDropdown/RolesDropdown.tsx
  packages/ui/src/components/Input/InputField.tsx
  packages/ui/src/components/Profile/Profile.css.ts
  packages/ui/src/components/Profile/Profile.tsx
  packages/utils/src/hooks/useDebounce.ts
  packages/utils/src/index.ts
Labels: ✨Feature, 🍀채원

#39 [feat] 2.5 배정현황 UI
  apps/web/src/app/(main)/apply-management/[tab]/@modal/(.)charge/page.tsx
  apps/web/src/app/(main)/apply-management/[tab]/@modal/default.tsx
  apps/web/src/app/(main)/apply-management/[tab]/TabClient.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[[...modal]]/page.tsx
  apps/web/src/app/(main)/apply-management/[tab]/layout.tsx
  apps/web/src/app/(main)/apply-management/_components/ActionToolbar/ActionToolbar.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyList/ApplyList.css.ts
  apps/web/src/app/(main)/apply-management/_components/ApplyList/ApplyList.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListHeader/ApplyListHeader.css.ts
  apps/web/src/app/(main)/apply-management/_components/ApplyListHeader/ApplyListHeader.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItem.css.ts
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItem.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItemFinal.tsx
  apps/web/src/app/(main)/apply-management/_components/EvalBubbles/EvalBubbles.css.ts
  apps/web/src/app/(main)/apply-management/_components/EvalBubbles/EvalBubbles.tsx
  apps/web/src/app/(main)/apply-management/_components/ModalContent/ChargeModalContent.css.ts
  apps/web/src/app/(main)/apply-management/_components/ModalContent/ChargeModalContent.tsx
  apps/web/src/app/(main)/apply-management/_components/ModalContent/ProfileChip/ProfileChip.tsx
  apps/web/src/app/(main)/apply-management/_components/ModalContent/ProfileListItem/ProfileListItem.tsx
  apps/web/src/app/(main)/apply-management/_components/SortMenu/SortMenu.css.ts
  apps/web/src/app/(main)/apply-management/_components/SortMenu/SortMenu.tsx
  apps/web/src/app/(main)/apply-management/_components/StatusBadge/StatusBadge.css.ts
  apps/web/src/app/(main)/apply-management/_components/StatusBadge/StatusBadge.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/DocumentTab/DocumentTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/FinalTab/FinalTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/InterViewTab/InterviewTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/RejectedTab/RejectedTab.tsx
  apps/web/src/app/(main)/apply-management/_components/TableContainer/TableContainer.css.ts
  apps/web/src/app/(main)/apply-management/_components/TableContainer/TableContainer.tsx
  apps/web/src/app/(main)/apply-management/layout.tsx
  apps/web/src/app/(main)/apply-management/page.tsx
  packages/ui/package.json
  packages/ui/src/components/DropDown/SelectDropdown/ChargeDropdown.tsx
  packages/ui/src/components/DropDown/index.ts
  packages/ui/src/components/TabBar/TabBar.tsx
  packages/ui/src/icons/assets/colored/ic_menu_btn.svg
  packages/ui/src/icons/assets/mono/ic_charge_btn.svg
  packages/ui/src/icons/assets/mono/ic_criteria_btn.svg
  packages/ui/src/icons/assets/mono/ic_file_btn.svg
  packages/ui/src/icons/assets/mono/ic_mail_btn.svg
  packages/ui/src/icons/assets/mono/ic_message_btn.svg
  packages/ui/src/icons/src/colored/IcMenuBtn.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/ui/src/icons/src/mono/IcChargeBtn.tsx
  packages/ui/src/icons/src/mono/IcCriteriaBtn.tsx
  packages/ui/src/icons/src/mono/IcFileBtn.tsx
  packages/ui/src/icons/src/mono/IcMailBtn.tsx
  packages/ui/src/icons/src/mono/IcMessageBtn.tsx
  packages/ui/src/icons/src/mono/index.ts
  packages/utils/src/util/tab.ts
Labels: ✨Feature, 🎨Design, 🍀채원

#61 [fix] 세세한 오류 수정
  apps/web/src/app/(auth)/join/_components/AgreementContent/AgreementContent.tsx
  apps/web/src/app/(auth)/join/_components/Step2/AgreementItem.tsx
  apps/web/src/app/(auth)/join/_components/Step2/Step2.css.ts
  apps/web/src/app/(auth)/join/_components/Step2/Step2.tsx
  apps/web/src/app/(auth)/layout.tsx
  apps/web/src/app/(main)/application-list/page.tsx
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Left/DateChip.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Left/LeftPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Right/RightPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/StageTab.css.ts
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/StageTab.tsx
  apps/web/src/app/(main)/application-list/setting/preview/_components/InfoField/InfoField.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItem.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItemFinal.tsx
  apps/web/src/app/(main)/apply-management/_components/AssignModalContent/AssignModalContent.tsx
  apps/web/src/app/(main)/apply-management/_components/ChargeModalContent/ChargeModalContent.tsx
  apps/web/src/app/(main)/apply-management/_components/ChargeModalContent/ProfileChip/ProfileChip.tsx
  apps/web/src/app/(main)/apply-management/_components/EvalBubbles/EvalBubbles.tsx
  apps/web/src/app/(main)/apply-management/add/page.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/ApplicantInterviewForm/ApplicantInterviewForm.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/InterviewQuestions/InterviewQuestions.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/AllCell.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/FilterForm/FilterForm.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/organization/_components/MemberAssignmentPanel/MemberAssignmentPanel.tsx
  apps/web/src/app/(main)/organization/_components/RolePalettePanel/RolePalettePanel.tsx
  apps/web/src/app/(main)/organization/_components/SettingsHeader/SettingsHeader.tsx
  apps/web/src/app/(main)/organization/settings/Settings.tsx
  apps/web/src/app/login/_components/LoginForm/LoginForm.tsx
  apps/web/src/store/mutation/useAddCommentMutation.ts
  apps/web/src/store/mutation/useDeleteRecruitmentMutation.ts
  apps/web/src/store/mutation/useDistributeEvaluators.ts
  apps/web/src/store/mutation/usePublishRecruitmentMutation.ts
  apps/web/src/store/mutation/useUpdateCommentMutation.ts
  apps/web/src/types/recruitment.ts
  apps/web/src/utils/color.ts
  apps/web/src/utils/convertDetailToForm.ts
  apps/web/src/utils/convertFormToRequest.ts
  packages/ui/src/components/Callout/Callout.css.ts
  packages/ui/src/components/Callout/Callout.tsx
  packages/ui/src/components/Callout/HoverCallout.tsx
  packages/ui/src/components/DatePicker/DatePicker.css.ts
  packages/ui/src/components/DropDown/DropdownList.tsx
  packages/ui/src/components/DropDown/DropdownRoot.tsx
  packages/ui/src/components/DropDown/DropdownTrigger.tsx
  packages/ui/src/components/DropDown/SelectDropdown/ClubDropdwon.tsx
  packages/ui/src/components/DropDown/SelectDropdown/RolesDropdown.tsx
  packages/ui/src/components/DropDown/context.ts
  packages/ui/src/components/Stepper/Stepper.css.ts
  packages/ui/src/components/Stepper/Stepper.tsx
  packages/ui/src/icons/assets/colored/ic_pencil.svg
  packages/ui/src/icons/assets/colored/ic_room_plus.svg
  packages/ui/src/icons/src/colored/IcPencil.tsx
  packages/ui/src/icons/src/colored/IcRoomPlus.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/utils/src/util/tag.ts
Labels: 🚧Fix, 🍀채원

#62 fix: 스크롤 없애기 (#60)
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Left/LeftPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Right/Panal/CommonSectionPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Right/RightPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/StageTab.tsx
Labels: 🔥Hotfix, 🍀채원
