Repository WITHUS-K/WITHUS-FE, pull requests merged in 2025-08, with the labels that each got.

#152 [fix] 빌드 오류 수정
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
Labels: 🔥Hotfix, 🌻유빈

#156 [feat] 자동배포
  .github/workflows/build-test.yml
  .github/workflows/git-push.yml
  apps/web/src/app/(main)/page.tsx
  build.sh
Labels: ✨Feature, 🍀채원

#159 [fix] 사용자 서류평가 QA 반영
  apps/web/src/app/(main)/docs-evaluation/(tabs)/[tab]/TabPageClient.tsx
  apps/web/src/app/(main)/docs-evaluation/application/[id]/_components/DocsEvaluation/DocsEvaluation.tsx
  apps/web/src/app/(main)/docs-evaluation/application/[id]/_components/EvaluationAddCommentCard/EvaluationAddCommentCard.tsx
  packages/ui/src/components/Memo/Memo.tsx
Labels: 🚧Fix, 🌻유빈
