Repository WITHUS-K/WITHUS-FE, pull requests merged in 2025-04, with the labels that each got.

#2 [design] 디자인시스템 세팅
  .github/workflows/chromatic.yml
  .prettierrc
  apps/web/public/font/subset-PretendardVariable.woff2
  apps/web/src/app/layout.tsx
  apps/web/src/app/page.tsx
  package.json
  packages/theme/esbuild.config.mjs
  packages/theme/package.json
  packages/theme/src/index.ts
  packages/theme/src/sprinkles/sprinkles.css.ts
  packages/theme/src/styles/global.css.ts
  packages/theme/src/styles/reset.css.ts
  packages/theme/src/themes/contract.ts
  packages/theme/src/themes/theme.css.ts
  packages/theme/src/tokens/colors.ts
  packages/theme/src/tokens/fontStyles.ts
  packages/theme/src/tokens/radius.ts
  packages/theme/src/tokens/tokens.ts
  packages/theme/src/tokens/typography.ts
  packages/theme/tsconfig.json
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/esbuild.config.mjs
  packages/ui/package.json
  packages/ui/src/Button/Button.stories.ts
  packages/ui/src/Button/Button.tsx
  packages/ui/src/Button/button.css
  packages/ui/src/components/Flex/Flex.css.ts
  packages/ui/src/components/Flex/Flex.stories.tsx
  packages/ui/src/components/Flex/Flex.tsx
  packages/ui/src/components/Text/Text.css.ts
  packages/ui/src/components/Text/Text.stories.tsx
  packages/ui/src/components/Text/Text.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/icons/assets/ic_logo.svg
  packages/ui/src/icons/src/IcLogo.tsx
  packages/ui/src/icons/src/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: 🔧Setting, 🎨Design, 🍀채원

#5 [feat] button, input, dropdown 컴포넌트
  packages/theme/esbuild.config.mjs
  packages/theme/package.json
  packages/theme/src/index.ts
  packages/theme/src/styles/reset.css.ts
  packages/theme/src/tokens/colors.ts
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/.storybook/preview.tsx
  packages/ui/package.json
  packages/ui/src/components/Button/Button.css.ts
  packages/ui/src/components/Button/Button.stories.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/DropDown/Dropdown.css.ts
  packages/ui/src/components/DropDown/DropdownItem.tsx
  packages/ui/src/components/DropDown/DropdownList.tsx
  packages/ui/src/components/DropDown/DropdownRoot.tsx
  packages/ui/src/components/DropDown/DropdownTrigger.tsx
  packages/ui/src/components/DropDown/SelectDropdown/SelectDropdown.stories.tsx
  packages/ui/src/components/DropDown/SelectDropdown/SelectDropdown.tsx
  packages/ui/src/components/DropDown/SelectDropdown/SelectDropdownTriggerContent.tsx
  packages/ui/src/components/DropDown/context.ts
  packages/ui/src/components/Input/BaseInput.tsx
  packages/ui/src/components/Input/Input.css.ts
  packages/ui/src/components/Input/InputField.stories.tsx
  packages/ui/src/components/Input/InputField.tsx
  packages/ui/src/components/Input/TextField.stories.tsx
  packages/ui/src/components/Input/TextField.tsx
  packages/ui/src/components/Text/Text.css.ts
  packages/ui/src/components/Text/Text.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/icons/assets/colored/ic_arrow_dropdown.svg
  packages/ui/src/icons/assets/colored/ic_input_error.svg
  packages/ui/src/icons/assets/colored/ic_input_search.svg
  packages/ui/src/icons/assets/colored/ic_pw_active.svg
  packages/ui/src/icons/assets/colored/ic_pw_default.svg
  packages/ui/src/icons/assets/ic_logo.svg
  packages/ui/src/icons/assets/mono/ic_button_ex.svg
  packages/ui/src/icons/src/IcLogo.tsx
  packages/ui/src/icons/src/colored/IcArrowDropdown.tsx
  packages/ui/src/icons/src/colored/IcInputError.tsx
  packages/ui/src/icons/src/colored/IcInputSearch.tsx
  packages/ui/src/icons/src/colored/IcPwActive.tsx
  packages/ui/src/icons/src/colored/IcPwDefault.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/ui/src/icons/src/index.ts
  packages/ui/src/icons/src/mono/IcButtonEx.tsx
  packages/ui/src/icons/src/mono/index.ts
  packages/ui/svgr.config.js
  packages/utils/package.json
  packages/utils/src/hooks/useOutsideClick.ts
  packages/utils/src/hooks/useOverlay.ts
  packages/utils/src/index.ts
  pnpm-lock.yaml
  turbo.json
Labels: ✨Feature, 🎨Design, 🍀채원

#7 [feat] Header, Sidebar 컴포넌트
  packages/ui/.storybook/main.ts
  packages/ui/src/components/Header/Header.css.ts
  packages/ui/src/components/Header/Header.stories.tsx
  packages/ui/src/components/Header/Header.tsx
  packages/ui/src/components/Header/HeaderLeft.tsx
  packages/ui/src/components/Header/HeaderRight.tsx
  packages/ui/src/components/Sidebar/Sidebar.css.ts
  packages/ui/src/components/Sidebar/Sidebar.stories.tsx
  packages/ui/src/components/Sidebar/Sidebar.tsx
  packages/ui/src/components/Sidebar/SidebarItem.tsx
  packages/ui/src/components/Sidebar/SidebarList.tsx
  packages/ui/src/icons/assets/colored/ic_header_logo.svg
  packages/ui/src/icons/assets/colored/ic_header_profile.svg
  packages/ui/src/icons/assets/mono/ic_header_alarm.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_calender.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_group.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_home.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_info.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_paper.svg
  packages/ui/src/icons/assets/mono/ic_sidebar_search.svg
  packages/ui/src/icons/assets/mono/ic_triangle_down.svg
  packages/ui/src/icons/src/colored/IcHeaderLogo.tsx
  packages/ui/src/icons/src/colored/IcHeaderProfile.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/ui/src/icons/src/mono/IcHeaderAlarm.tsx
  packages/ui/src/icons/src/mono/IcSidebarCalender.tsx
  packages/ui/src/icons/src/mono/IcSidebarGroup.tsx
  packages/ui/src/icons/src/mono/IcSidebarHome.tsx
  packages/ui/src/icons/src/mono/IcSidebarInfo.tsx
  packages/ui/src/icons/src/mono/IcSidebarPaper.tsx
  packages/ui/src/icons/src/mono/IcSidebarSearch.tsx
  packages/ui/src/icons/src/mono/IcTriangleDown.tsx
  packages/ui/src/icons/src/mono/index.ts
Labels: ✨Feature, 🎨Design, 🌻유빈

#9 [feat] Tags, Pagination, List, Profile 컴포넌트
  packages/theme/src/styles/global.css.ts
  packages/ui/src/components/Chips/Chip/Chip.css.ts
  packages/ui/src/components/Chips/Chip/Chip.stories.tsx
  packages/ui/src/components/Chips/Chip/Chip.tsx
  packages/ui/src/components/Chips/InputChip/InputChip.css.ts
  packages/ui/src/components/Chips/InputChip/InputChip.stories.ts
  packages/ui/src/components/Chips/InputChip/InputChip.tsx
  packages/ui/src/components/Chips/ProfileChip/ProfileChip.css.ts
  packages/ui/src/components/Chips/ProfileChip/ProfileChip.stories.tsx
  packages/ui/src/components/Chips/ProfileChip/ProfileChip.tsx
  packages/ui/src/components/Chips/ScoreChip/ScoreChip.css.ts
  packages/ui/src/components/Chips/ScoreChip/ScoreChip.stories.tsx
  packages/ui/src/components/Chips/ScoreChip/ScoreChip.tsx
  packages/ui/src/components/Header/Header.css.ts
  packages/ui/src/components/Header/HeaderLeft.tsx
  packages/ui/src/components/Header/HeaderRight.tsx
  packages/ui/src/components/List/List.css.ts
  packages/ui/src/components/List/List.stories.tsx
  packages/ui/src/components/List/List.tsx
  packages/ui/src/components/List/ListLayout.tsx
  packages/ui/src/components/Pagination/Pagination.css.ts
  packages/ui/src/components/Pagination/Pagination.stories.tsx
  packages/ui/src/components/Pagination/Pagination.tsx
  packages/ui/src/components/Profile/Profile.css.ts
  packages/ui/src/components/Profile/Profile.stories.tsx
  packages/ui/src/components/Profile/Profile.tsx
  packages/ui/src/icons/assets/colored/ic_delete.svg
  packages/ui/src/icons/assets/mono/ic_arrow_left.svg
  packages/ui/src/icons/assets/mono/ic_arrow_right.svg
  packages/ui/src/icons/src/colored/IcDelete.tsx
  packages/ui/src/icons/src/colored/index.ts
  packages/ui/src/icons/src/mono/IcArrowLeft.tsx
  packages/ui/src/icons/src/mono/IcArrowRight.tsx
  packages/ui/src/icons/src/mono/index.ts
Labels: ✨Feature, 🎨Design, 🌻유빈

#16 [feat] 면접 관리 페이지 UI
  apps/web/src/app/(main)/interview-evaluation/_components/CellRender/InterviewerCell.tsx
  apps/web/src/app/(main)/interview-management/_components/ApplicantDetailContent/ApplicantDetailContent.css.ts
  apps/web/src/app/(main)/interview-management/_components/ApplicantDetailContent/ApplicantDetailContent.tsx
  apps/web/src/app/(main)/interview-management/_components/ApplicantHeader/ApplicantHeader.css.ts
  apps/web/src/app/(main)/interview-management/_components/ApplicantHeader/ApplicantHeader.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/AllCell.tsx
  apps/web/src/app/(main)/interview-management/_components/DataController/DataController.css.ts
  apps/web/src/app/(main)/interview-management/_components/DataController/DataController.tsx
  apps/web/src/app/(main)/interview-management/layout.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/[time]/layout.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/[time]/page.css.ts
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/[time]/page.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/layout.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/components/TimeTable/TimeTable.tsx
  apps/web/src/constants/timetable.ts
  apps/web/tsconfig.json
  packages/ui/.storybook/main.ts
  packages/ui/package.json
  packages/ui/src/components/Comment/Comment.css.ts
  packages/ui/src/components/Comment/Comment.stories.tsx
  packages/ui/src/components/Comment/Comment.tsx
  packages/ui/src/components/Comment/index.ts
  packages/ui/src/components/Divider/Divider.css.ts
  packages/ui/src/components/Divider/Divider.stories.tsx
  packages/ui/src/components/Divider/Divider.tsx
  packages/ui/src/components/Divider/index.ts
  packages/ui/src/components/FileUploader/FileUploader.css.ts
  packages/ui/src/components/FileUploader/FileUploader.stories.tsx
  packages/ui/src/components/FileUploader/FileUploader.tsx
  packages/ui/src/components/FileUploader/index.ts
  packages/ui/src/components/List/AccordianList/AccordianList.css.ts
  packages/ui/src/components/List/AccordianList/AccordianList.stories.tsx
  packages/ui/src/components/List/AccordianList/AccordianList.tsx
  packages/ui/src/components/List/Accordion/AccordionContent.tsx
  packages/ui/src/components/List/Accordion/AccordionContext.tsx
  packages/ui/src/components/List/Accordion/AccordionItem.tsx
  packages/ui/src/components/List/Accordion/AccordionRoot.tsx
  packages/ui/src/components/List/Accordion/AccordionTrigger.tsx
  packages/ui/src/components/List/List.css.ts
  packages/ui/src/components/List/List.tsx
  packages/ui/src/components/List/ListLayout.tsx
  packages/ui/src/components/List/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/hooks/useAccordionItem.tsx
  packages/ui/src/icons/assets/colored/ic_download.svg
  packages/ui/src/icons/src/colored/IcDownload.tsx
  packages/ui/src/icons/src/colored/index.ts
Labels: ✨Feature, 🎨Design, 🌻유빈
