Repository WITHUS-K/WITHUS-FE, pull requests merged in 2025-07, with the labels that each got.

#75 [hotfix] 미리보기 오류 해결
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
Labels: 🔥Hotfix, 🍀채원

#73 [refactor] 로그인/회원가입 QA 및 데이트피커 리팩토링
  apps/web/src/app/(auth)/join/_components/Step3/Step3Admin.tsx
  apps/web/src/app/(auth)/join/_components/Step3/Step3User.tsx
  apps/web/src/app/(main)/apply-management/add/_components/BasicInfoForm/BasicInfoForm.tsx
  apps/web/src/app/(main)/interview-evaluation/page.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/page.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/interview-management/page.tsx
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.css.ts
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.tsx
  apps/web/src/app/login/_components/LoginForm/LoginForm.tsx
  apps/web/src/store/query/useOrganizationInterviewsQuery.ts
  packages/ui/package.json
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/DatePicker/DatePicker.css.ts
  packages/ui/src/components/DatePicker/DatePicker.stories.tsx
  packages/ui/src/components/DatePicker/DatePicker.tsx
  packages/ui/src/components/DatePicker/MonthOnlySelect.tsx
  packages/ui/src/components/DatePicker/YearSelect.tsx
  packages/ui/src/components/Header/Header.tsx
  packages/ui/src/components/Header/HeaderRight.tsx
  packages/ui/src/components/Spinner/Spinner.css.ts
  packages/ui/src/components/Spinner/Spinner.tsx
  packages/ui/src/components/Stepper/Stepper.css.ts
  packages/ui/src/components/index.ts
Labels: ♻️Refactor, 🚧Fix, 🌻유빈

#77 [refactor] 지원자용 지원서 QA
  apps/web/src/app/(main)/apply-management/add/_components/ApplicationPartsForm/ApplicationPartsForm.tsx
  apps/web/src/app/(main)/apply-management/add/_components/BasicInfoForm/BasicInfoForm.css.ts
  apps/web/src/app/(main)/apply-management/add/_components/BasicInfoForm/BasicInfoForm.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.css.ts
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.tsx
  apps/web/src/app/apply/[organization]/[slug]/layout.css.ts
  apps/web/src/app/apply/[organization]/[slug]/layout.tsx
  apps/web/src/app/apply/[organization]/[slug]/mobile-only/page.tsx
  apps/web/src/app/apply/[organization]/[slug]/submitted/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/loading.tsx
  apps/web/src/components/FileUpload/FileUpload.css.ts
  apps/web/src/components/FileUpload/FileUpload.tsx
  apps/web/src/components/QuestionFileListForm/QuestionFileListForm.tsx
  packages/ui/src/components/DatePicker/DatePicker.tsx
  packages/ui/src/components/Input/Input.css.ts
  packages/ui/src/components/Input/QuestionInput.tsx
  packages/ui/src/components/Option/Option.tsx
  packages/ui/src/hooks/useModal.tsx
  packages/ui/src/icons/assets/colored/ic_annotation_alert.svg
  packages/ui/src/icons/assets/colored/ic_application_file_upload_co.svg
  packages/ui/src/icons/src/colored/IcAnnotationAlert.tsx
  packages/ui/src/icons/src/colored/IcApplicationFileUploadCo.tsx
  packages/ui/src/icons/src/colored/index.ts
Labels: ✨Feature, ♻️Refactor, 🚧Fix, 🌻유빈

#80 [feat] opengraph metadata 적용
  apps/web/public/opengraph-image.png
  apps/web/src/app/layout.tsx
  apps/web/src/constants/metadata.ts
Labels: ✨Feature, 🌻유빈

#83 [hotfix] 미리보기 제한글자 오류 수정
  apps/web/src/app/(main)/application-list/setting/(preview)/_components/QuestionFileList/QuestionFileList.tsx
  apps/web/src/app/(main)/apply-management/[tab]/PageClient.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/DocumentTab/DocumentTab.tsx
  packages/ui/src/components/Input/QuestionInput.tsx
Labels: 🔥Hotfix, 🍀채원

#85 [feat] google analytics 추가
  apps/web/src/app/layout.tsx
  apps/web/src/components/GoogleAnalytics/GoogleAnalytics.tsx
Labels: ✨Feature, 🍀채원

#86 [feat] 쿠키 옵션 수정
  apps/web/src/api/auth.ts
  apps/web/src/api/authCookies.ts
  apps/web/src/api/login.ts
  apps/web/src/app/(main)/AuthLayout.tsx
  apps/web/src/components/Sidebar/Sidebar.tsx
Labels: ✨Feature, 🍀채원

#87 [fix] : 쿠키 옵션 수정
  apps/web/src/api/authCookies.ts
Labels: 🚧Fix, 🍀채원

#89 [hotfix] 토큰으로 받아오는 걸로 수정
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
  apps/web/src/app/(main)/apply-management/_components/AssignModalContent/AssignModalContent.tsx
  apps/web/src/app/(main)/apply-management/_components/ChargeModalContent/ChargeModalContent.tsx
  apps/web/src/app/(main)/docs-evaluation/application/[id]/DetailClient.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/ApplicantInterviewForm/ApplicantInterviewForm.tsx
  apps/web/src/app/(main)/interview-evaluation/page.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/page.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/interview-management/_components/InviteModalContent/InviteModalContent.tsx
  apps/web/src/app/(main)/organization/@modal/(.)invite/page.tsx
  apps/web/src/app/(main)/organization/[[...modal]]/page.tsx
  apps/web/src/store/mutation/useLoginMutation.ts
  apps/web/src/store/state/userStore.ts
  apps/web/src/utils/getClientSideTokens.ts
Labels: 🚧Fix, 🍀채원

#95 [hotfix] 지원자용 지원서 성별, 생일 디테일 수정
  apps/web/src/app/(main)/apply-management/add/_components/BasicInfoForm/BasicInfoForm.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/store/mutation/useCreateApplication.ts
Labels: 🔥Hotfix, 🍀채원

#98 [fix] 미들웨어 public 추가
  apps/web/src/components/GoogleAnalytics/GoogleAnalytics.tsx
  apps/web/src/middleware.ts
Labels: 🚧Fix, 🍀채원

#103 [hotfix] TextField 안보이는 에러 수정
  packages/ui/src/components/Input/QuestionInput.tsx
Labels: 🔥Hotfix, 🌻유빈

#110 [feat] 지원서 지원마감 로직 추가
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.css.ts
  apps/web/src/app/apply/[organization]/[slug]/_components/FormNavigator/FormNavigator.tsx
  apps/web/src/app/apply/[organization]/[slug]/end/page.tsx
  apps/web/src/app/apply/[organization]/[slug]/page.tsx
  apps/web/src/app/loading.tsx
  apps/web/src/middleware.ts
  apps/web/src/store/mutation/useCreateApplication.ts
  apps/web/src/store/query/useRecruitmentBySlugQuery.ts
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/DropDown/SelectDropdown/ClubDropdwon.tsx
  packages/ui/src/components/Input/QuestionInput.tsx
  packages/ui/src/components/Spinner/Spinner.tsx
  packages/ui/src/components/Spinner/index.ts
Labels: ✨Feature, 🚧Fix, 🍀채원

#111 [fix] 관리자 서류 부분 QA 반영
  apps/web/src/api/fetch.ts
  apps/web/src/app/(main)/application-list/setting/(preview)/PreviewComponent.tsx
  apps/web/src/app/(main)/application-list/setting/(preview)/_components/QuestionFileList/QuestionFileList.css.ts
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Left/LeftPanel.tsx
  apps/web/src/app/(main)/application-list/setting/_components/StageTab/Right/Panal/FinalPanel.tsx
  apps/web/src/app/(main)/apply-management/[tab]/@modal/(.)assign-manager/page.tsx
  apps/web/src/app/(main)/apply-management/[tab]/PageClient.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[id]/ApplicationDetailClient.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[id]/_components/ApplicantDetail/ApplicantDetail.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[id]/_components/InterviewScheduleViewer/InterviewScheduleViewer.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[id]/page.tsx
  apps/web/src/app/(main)/apply-management/[tab]/layout.css.ts
  apps/web/src/app/(main)/apply-management/[tab]/layout.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyList/ApplyList.css.ts
  apps/web/src/app/(main)/apply-management/_components/ApplyList/ApplyList.tsx
  apps/web/src/app/(main)/apply-management/_components/ApplyListItem/ApplyListItem.tsx
  apps/web/src/app/(main)/apply-management/_components/AssignModalContent/AssignModalContent.tsx
  apps/web/src/app/(main)/apply-management/_components/StatusBadge/StatusBadge.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/DocumentTab/DocumentTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/FinalTab/FinalTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/InterViewTab/InterviewTab.tsx
  apps/web/src/app/(main)/apply-management/_components/Tab/RejectedTab/RejectedTab.tsx
  apps/web/src/app/(main)/apply-management/_components/TableContainer/TableContainer.tsx
  apps/web/src/app/(main)/apply-management/add/AddApplicantClient.tsx
  apps/web/src/app/(main)/organization/OrganizationPageClient.tsx
  apps/web/src/app/(main)/organization/_components/OrgList/OrgList.css.ts
  apps/web/src/app/(main)/organization/_components/OrgList/OrgList.tsx
  apps/web/src/app/(main)/organization/layout.css.ts
  apps/web/src/app/(main)/organization/layout.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/store/mutation/useCreateApplication.ts
  apps/web/src/store/mutation/useDistributeEvaluators.ts
  apps/web/src/store/mutation/useFileDownload.ts
  apps/web/src/store/query/useAdminApplicationsQuery.ts
  apps/web/src/types/application.ts
  apps/web/src/utils/convertFormToRequest.ts
  packages/ui/src/components/Callout/Callout.tsx
  packages/ui/src/components/DropDown/SelectDropdown/StatusDropdown.tsx
  packages/ui/src/components/DropDown/SelectDropdown/StatusDropdownTriggerContent.tsx
Labels: 🚧Fix, 🍀채원

#116 [fix] 지원자 들어오면 공고 수정 불가하게
  apps/web/src/app/(main)/application-list/ApplicationListClient.tsx
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
Labels: 🚧Fix, 🍀채원

#118 [fix] 메일 전송 관련 오류 수정
  apps/web/src/app/(main)/apply-management/_components/SideTabs/MailSideTab/MailSideTab.tsx
  apps/web/src/app/(main)/apply-management/_components/SideTabs/RichTextEditor/RichTextEditor.tsx
Labels: 🚧Fix, 🌻유빈

#120 [feat] 서류 3단계 평가 로직 구현
  apps/web/src/app/(main)/docs-evaluation/application/[id]/_components/DocsEvaluation/DocsEvaluation.css.ts
  apps/web/src/app/(main)/docs-evaluation/application/[id]/_components/DocsEvaluation/DocsEvaluation.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/app/apply/[organization]/[slug]/end/page.tsx
  packages/ui/src/icons/assets/colored/ic_expired_date_lg.svg
  packages/ui/src/icons/assets/colored/ic_expired_date_sm.svg
  packages/ui/src/icons/src/colored/IcExpiredDateLg.tsx
  packages/ui/src/icons/src/colored/IcExpiredDateSm.tsx
  packages/ui/src/icons/src/colored/index.ts
Labels: ✨Feature, 🌻유빈

#121 [hotfix] 지원서 필수질문 아니면 빈값으로 넘기게 (text만)
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/interview-management/layout.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/store/mutation/useCreateScheduleMutation.ts
Labels: 🔥Hotfix, 🍀채원

#123 [fix] 면접 디테일 수정
  apps/web/src/app/(main)/apply-management/[tab]/[id]/ApplicationDetailClient.tsx
  apps/web/src/app/(main)/apply-management/[tab]/[id]/_components/ApplicantDetail/ApplicantDetail.tsx
  apps/web/src/app/(main)/docs-evaluation/(tabs)/[tab]/TabPageClient.tsx
  apps/web/src/app/(main)/docs-evaluation/application/[id]/DetailClient.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/ApplicantInterviewForm/ApplicantInterviewForm.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/[id]/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/page.tsx
  apps/web/src/app/(main)/interview-management/_components/ApplicantDetailContent/ApplicantDetailContent.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/ApplicantCell.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/CellRenders.css.ts
  apps/web/src/app/(main)/interview-management/_components/CellRenders/GuideCell.tsx
  apps/web/src/app/(main)/interview-management/_components/CellRenders/InterviewerCell.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/application/[time]/page.tsx
  apps/web/src/components/FileUpload/FileUpload.tsx
  apps/web/src/components/ProfileGroup/ProfileGroup.css.ts
  apps/web/src/components/ProfileGroup/ProfileGroup.tsx
  apps/web/src/constants/timetable.ts
  apps/web/src/store/mutation/useAddCommentMutation.ts
  apps/web/src/store/mutation/useAddEvaluationMutation.ts
  apps/web/src/store/mutation/useCreateScheduleMutation.ts
  apps/web/src/store/query/useApplicationDetailQuery.ts
  apps/web/src/store/query/useTimeSlotApplicationsQuery.ts
  apps/web/src/types/application.ts
  packages/ui/src/components/FileUploader/FileUploader.tsx
  packages/ui/src/components/List/AccordianList/AccordianList.tsx
  packages/ui/src/components/Profile/Profile.css.ts
  packages/ui/src/components/Profile/Profile.tsx
Labels: 🚧Fix, 🍀채원

#124 [hofix] 한글 이름의 파일 다운로드 안되는 이슈 해결
  apps/web/src/store/mutation/useFileDownload.ts
Labels: 🔥Hotfix, 🍀채원

#127 [refactor] 면접 부분 ssr 적용 및 디테일 수정
  apps/web/package.json
  apps/web/public/images/profile.png
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
  apps/web/src/app/(main)/apply-management/_components/SortMenu/SortMenu.css.ts
  apps/web/src/app/(main)/docs-evaluation/(tabs)/[tab]/TabPageClient.tsx
  apps/web/src/app/(main)/interview-evaluation/EvaluationClient.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/CellRender/GuideCell.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/CellRender/InterviewerCell.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/EvaluationHeader/EvaluationHeader.tsx
  apps/web/src/app/(main)/interview-evaluation/page.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/ScheduleClient.tsx
  apps/web/src/app/(main)/interview-evaluation/schedule/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/EvaluationTimetableClient.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/[id]/ApplicantDetailClient.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/[id]/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/[tab]/page.tsx
  apps/web/src/app/(main)/interview-evaluation/timetable/layout.tsx
  apps/web/src/app/(main)/interview-management/InterviewManagementPageClient.tsx
  apps/web/src/app/(main)/interview-management/_components/ApplicantHeader/ApplicantHeader.tsx
  apps/web/src/app/(main)/interview-management/layout.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/TimeTableClient.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/[[...modal]]/page.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/application/[time]/ApplicantDetailClient.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/application/[time]/page.tsx
  apps/web/src/app/(main)/interview-management/timetable/[tab]/[date]/layout.tsx
  apps/web/src/store/mutation/useRegisterAvailabilitiesMutation.ts
  apps/web/src/store/query/useInterviewScheduleQuery.ts
  apps/web/src/store/query/useMyTimeSlotsQuery.ts
  apps/web/src/store/query/useOrganizationInterviewsQuery.ts
  apps/web/src/store/query/useRecruitmentsListQuery.ts
  apps/web/src/store/query/useTimeSlotApplicationsQuery.ts
  packages/ui/src/components/DropDown/Dropdown.css.ts
  packages/ui/src/components/Profile/Profile.tsx
  packages/ui/src/icons/assets/colored/ic_docs_non.svg
  packages/ui/src/icons/assets/colored/ic_schedule.svg
  packages/ui/src/icons/src/colored/IcDocsNon.tsx
  packages/ui/src/icons/src/colored/IcSchedule.tsx
  packages/ui/src/icons/src/colored/index.ts
  pnpm-lock.yaml
Labels: ♻️Refactor, 🍀채원

#132 [fix] 면접 부분 로직 수정 (2차)
  apps/web/src/app/(main)/interview-evaluation/EvaluationClient.tsx
  apps/web/src/app/(main)/interview-evaluation/_components/EvaluationHeader/EvaluationHeader.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/FilterForm/FilterForm.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/interview-management/layout.tsx
  apps/web/src/app/(main)/organization/settings/Settings.tsx
  apps/web/src/store/mutation/useResetInterviewScheduleMutation.ts
  apps/web/src/store/mutation/useUpdateOrganizationRoleMutation.ts
  apps/web/src/store/query/useInterviewScheduleQuery.ts
  packages/ui/src/components/Header/HeaderRight.tsx
  packages/ui/src/components/Stepper/Stepper.tsx
  packages/ui/src/icons/assets/mono/ic_re.svg
  packages/ui/src/icons/src/mono/IcRe.tsx
  packages/ui/src/icons/src/mono/index.ts
Labels: 🚧Fix, 🍀채원

#134 [hotfix] 지원서 제출 버튼 활성화 조건 추가
  apps/web/src/app/(main)/application-list/ApplicationListClient.tsx
  apps/web/src/app/(main)/application-list/setting/_components/CriteriaTabs/CriteriaDocsTab/CriteriaDocsTab.tsx
  apps/web/src/app/(main)/application-list/setting/_components/CriteriaTabs/CriteriaInterviewTab/CriteriaInterviewTab.tsx
  apps/web/src/app/(main)/application-list/setting/_components/CriteriaTabs/Section/EvaluationSection.tsx
  apps/web/src/app/(main)/application-list/setting/_components/SettingForm/SettingForm.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
  apps/web/src/app/(main)/organization/settings/Settings.tsx
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
Labels: 🔥Hotfix, 🍀채원

#137 [fix] 회원가입 비밀번호 특수기호 조건 추가 및 타임테이블 버튼 라이팅 수정
  apps/web/src/app/(auth)/join/_components/Step3/Step3Admin.tsx
  apps/web/src/app/(auth)/join/_components/Step3/Step3User.tsx
  apps/web/src/app/(main)/interview-management/_components/Filters/Filters.tsx
Labels: 🚧Fix, 🍀채원

#140 [fix] 조직관리 순번 오류
  apps/web/src/app/(main)/organization/_components/OrgList/OrgList.tsx
Labels: 🚧Fix, 🍀채원

#142 [hotfix] 큐시즘 공고에서 프론트엔드 파트만 필터링되게 임시구현
  apps/web/src/app/apply/[organization]/[slug]/ApplicationClient.tsx
  apps/web/src/app/apply/[organization]/[slug]/page.tsx
Labels: 🔥Hotfix, 🍀채원

#144 [fix] 담당자 프로필 hoverCallout 으로 변경
  apps/web/src/app/(main)/apply-management/_components/EvalBubbles/EvalBubbles.tsx
  packages/ui/src/components/Callout/Callout.css.ts
Labels: 🚧Fix, 🍀채원

#146 [hotfix] 문자 메일 탭 스크롤 되게
  apps/web/src/app/(main)/apply-management/_components/SideTabs/MailSideTab/MailSideTab.css.ts
Labels: 🔥Hotfix, 🍀채원
